import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/') })

test('filter, ON/OFF and selectable item models work with disabled states', async ({ page }) => {
  const section = page.locator('#game')
  const filter = section.getByRole('button', { name: '筛选课程' })
  await expect(filter).toHaveAttribute('aria-pressed', 'false')
  await filter.click()
  await expect(filter).toHaveAttribute('aria-pressed', 'true')
  await expect(filter).toContainText('2')
  const voice = section.getByRole('radiogroup', { name: '原作语音设置' })
  await voice.getByRole('radio', { name: 'OFF', exact: true }).click()
  await expect(voice.getByRole('radio', { name: 'OFF', exact: true })).toBeChecked()
  await expect(section).toContainText('语音：关闭')
  await voice.getByRole('radio', { name: 'OFF', exact: true }).press('ArrowLeft')
  await expect(voice.getByRole('radio', { name: 'ON', exact: true })).toBeChecked()
  await expect(section.getByRole('radiogroup', { name: '禁用语音设置' }).getByRole('radio')).toHaveCount(2)
  for (const radio of await section.getByRole('radiogroup', { name: '禁用语音设置' }).getByRole('radio').all()) await expect(radio).toBeDisabled()
  const favorite = section.getByRole('button', { name: '收藏当前课程' })
  await favorite.focus()
  await favorite.press('Space')
  await expect(favorite).toHaveAttribute('aria-pressed', 'true')
  await expect(section.getByRole('button', { name: '暂不可收藏' })).toBeDisabled()
})

test('selection group keeps one selected item and skips disabled choices with keyboard', async ({ page }) => {
  const group = page.getByRole('radiogroup', { name: '练习课程' })
  const first = group.getByRole('radio', { name: '歌唱练习', exact: true })
  await first.focus()
  await first.press('ArrowDown')
  const second = group.getByRole('radio', { name: '舞蹈练习', exact: true })
  await expect(second).toBeChecked()
  await expect(first).not.toBeChecked()
  await expect(page.locator('#game')).toContainText('当前课程：dance')
  await expect(group.getByRole('radio', { name: '未开放课程' })).toBeDisabled()
  await second.press('ArrowDown')
  await expect(first).toBeChecked()
})

test('game skins preserve input errors, tab navigation and dialog focus behavior', async ({ page }) => {
  const section = page.locator('#game')
  await expect(section.getByRole('heading', { name: '课程与设置' })).toBeVisible()
  await expect(section.getByRole('img', { name: '新内容' })).toHaveCount(2)
  const input = section.getByLabel('原作名称输入')
  await input.fill('')
  await expect(input).toHaveAttribute('aria-invalid', 'true')
  await expect(section.getByRole('alert')).toHaveText('请输入名称。')
  await input.fill('闪耀制作人')
  await expect(input).toHaveAttribute('aria-invalid', 'false')
  await section.getByRole('tab', { name: '详情', exact: true }).click()
  await expect(section.getByRole('tabpanel')).toContainText('保留原作纹理')
  const trigger = section.getByRole('button', { name: '原作弹窗', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: '原作确认弹窗' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('弹窗名称')).toHaveValue('闪耀制作人')
  for (let i = 0; i < 4; i++) {
    await page.keyboard.press('Tab')
    expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
  }
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
})

test('loader announces its active state, blocks local content and respects reduced motion', async ({ page }) => {
  const section = page.locator('#game')
  await section.getByRole('button', { name: '演示加载' }).click()
  await expect(section.getByRole('status', { name: '正在读取课程' })).toBeVisible()
  await expect(section.locator('.game-demo-loading > div').first()).toHaveAttribute('inert', '')
  await expect(section.getByRole('status', { name: '正在读取课程' })).toHaveCount(0)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(section.getByRole('status', { name: '小号加载' }).locator('.sc-loader__indicator')).toHaveCSS('animation-name', 'none')
})

test('game controls and skinned dialogs fit narrow screens', async ({ page }) => {
  for (const width of [320, 390, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    await page.locator('#game').scrollIntoViewIfNeeded()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.locator('#game .showcase-section__stage').screenshot({ path: `test-results/game-${width}.png`, animations: 'disabled', style: '.demo-sidebar, .demo-topbar, .skip-link { visibility: hidden; }' })
    await page.locator('#game').getByRole('button', { name: '原作弹窗', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '原作确认弹窗' })
    const bounds = await dialog.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    await page.screenshot({ path: `test-results/game-dialog-${width}.png`, animations: 'disabled' })
    await page.keyboard.press('Escape')
  }
})
